GrillRoastBaste2/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GrillRoastBaste2.Models;

namespace GrillRoastBaste2.Controllers
{
    
    public class AdminController : Controller
    {

        public ActionResult Delete(int ID)
        {
            CustomerDbContext context = new CustomerDbContext();
            var customerToDelete = context.Customers.Find(ID);
            context.Customers.Remove(customerToDelete);
            context.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Edit(int ID)
        {
            CustomerDbContext context = new CustomerDbContext();
            var customerToEdit = context.Customers.Find(ID);
    

            return View(customerToEdit);
        }

        [HttpPost]
        public ActionResult Edit(int? ID)
        {

            ViewBag.StatusList = GetStatusList();//Not sure how else to do this, getting an error when posting this
                                                 //didnt want to duplicate code so moved to a method but doesnt feel
                                                 //like a good solution.
                                                 //(error)there is no status list object, need to look at tempdata maybe?

            using (var context = new CustomerDbContext()) //uses the db context to add the customer sub to the db
            {
                

                if (ID == null)
                {
                    var result = new HttpNotFoundResult("No User ID associated with this customer");
                    return result;
                }
                
                var customerToUpdate = context.Customers.Find(ID);
                TryUpdateModel(customerToUpdate);
                if (ModelState.IsValid)
                {

                    try
                    {
                        context.SaveChanges();
                        return View("Index", context.Customers.ToList());
                    }
                    catch (Exception)
                    {
                        ModelState.AddModelError("", "Unable to edit the customer");
                    }

                }
             return View(customerToUpdate);
                
            }
           

        }

        [Authorize]
        public ActionResult Index(string sortOrder, string searchString, string StatusList)
        {
            CustomerDbContext context = new CustomerDbContext();
            ViewBag.StatusList = GetStatusList();

            ViewBag.NameSort = sortOrder == "name" ? "name_desc" : "name";
            ViewBag.NameSort = sortOrder == "surname" ? "surname_desc" : "surname";
            ViewBag.DateSort = sortOrder == "date" ? "date_desc" : "date";
            
            var customers = from c in context.Customers select c;
            //Should use a switch here
            if(StatusList == "0")
            {
                customers = customers.Where(x => ((int)x.Status == 0));
            }
            if (StatusList == "1")
            {
                customers = customers.Where(x => ((int)x.Status == 1));
            }
            if (StatusList == "2")
            {
                customers = customers.Where(x => ((int)x.Status == 2));
            }
            if (StatusList == "3")
            {
                customers = customers.Where(x => ((int)x.Status == 3));
            }


            if (searchString != null)
            {
                customers = customers.Where(x => x.Name.Contains(searchString) || x.SurName.Contains(searchString));
            }


            switch (sortOrder)
            {
                case "name":
                    {
                        customers = customers.OrderByDescending(x => x.Name);
                        break;
                    }
                case "name_desc":
                    {
                        customers = customers.OrderBy(x => x.Name);
                    }
                        break;
                case "surname":
                    {
                        customers = customers.OrderByDescending(x => x.Name);
                        break;
                    }
                case "surname_desc":
                    {
                        customers = customers.OrderBy(x => x.Name);
                    }
                    break;
                case "date":
                    {
                        customers = customers.OrderByDescending(x => x.DateOfEvent);
                        break;
                    }
                case "date_desc":
                    {
                        customers = customers.OrderBy(x => x.DateOfEvent);
                    }
                    break;
                default:
                    {
                        customers = customers.OrderBy(x => x.DateOfEvent);
                    }
                    break;
            }
            
           

            return View(customers.ToList());
        }

        public List<SelectListItem> GetStatusList()
        {
            List<SelectListItem> statusList = new List<SelectListItem>();
            statusList.Add(new SelectListItem { Text = "New", Value = "0", Selected = true });
            statusList.Add(new SelectListItem { Text = "Replied", Value = "1" });
            statusList.Add(new SelectListItem { Text = "Secured", Value = "2" });
            statusList.Add(new SelectListItem { Text = "Done", Value = "3" });
            statusList.Add(new SelectListItem { Text = "All", Value = "4" });
            return statusList;
        }
    }
}

GrillRoastBaste2/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GrillRoastBaste2.Controllers
{
    public class GalleryController : Controller
    {
        //TO-DO: add list of url strings which is passed to the view to populate the gallery
        //and add an associated view model to validate strings etc
        public ActionResult Index()
        {
            return View();
        }
    }
}

GrillRoastBaste2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GrillRoastBaste2.Models;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Web.Mvc.Html;

namespace GrillRoastBaste2.Controllers
{
    public class HomeController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }

        //TO-DO: add functionality for admins to upload/delete menus from the menus section
        public ActionResult Menus()
        {
            return View();
        }

        public ActionResult OurStory()
        {
            return View();
        }


        [HttpGet]
        public ViewResult Book()
        {
            return View();
        }

        [HttpPost]
        public ViewResult Book(CustomerSubmition customerSubmition)
        {
            if (ModelState.IsValid)
            { 
                customerSubmition.DateOfBooking = DateTime.Now; //Set the date and time when the booking is made

                var body = "<p>Hello! <strong>" + customerSubmition.Name + " " + customerSubmition.SurName + 
                    "</strong>, " + "Thank you for choosing GrillRoastBaste for your event.<br> One of our dedicated team members will be in touch</p>";
                var message = new MailMessage();
                message.To.Add(new MailAddress(customerSubmition.Email));
                message.From = new MailAddress("mattsykesbbg@gmail.com"); //Change to grillroastbaste email
                message.Subject = "Booking Enquiry Confirmation GrillRoastBaste";
                message.Body = body; //need to add footer to email for contact links
                message.IsBodyHtml = true;

                using (var smtp = new SmtpClient()) //Smtp set up and send
                {
                    var credential = new NetworkCredential()
                    {
                        UserName = "mattsykesbbg@gmail.com", //change for grillroastbaste user + pass
                        Password = "stunl0ck123" //need to store credentials more securely in a Database
                    };

                    smtp.Credentials = credential;
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 587;
                    smtp.EnableSsl = true;
                    smtp.Send(message);
                }

                using (var context = new CustomerDbContext()) //uses the db context to add the customer sub to the db
                {
                    context.Customers.Add(customerSubmition);
                    context.SaveChanges();
                }

                return View("ThankYou", customerSubmition);
            }
            else
            {
                return View();
            }
        }



    }
}

GrillRoastBaste2/Views/Shared/_Home.cshtml
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="~/Content/bootstrap-social-gh-pages/bootstrap-social.css"/>
        <link rel="stylesheet" href="~/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/Content/StyleSheet.css"/>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <meta name="viewport" content="width=device-width initial-scale=1" />
        <title>@Page.Title</title>
        @RenderSection("head", required: false)
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="@Url.Action("Index","Home")">GrillRoastBaste</a>
                    <a href="http://www.twitter.com" class="btn btn-social-icon btn-twitter navbar-btn"><span class="fa fa-twitter"></span></a>
                    <a href="http://www.facebook.com" class="btn btn-social-icon btn-facebook navbar-btn"><span class="fa fa-facebook"></span></a>
                    <a href="http://www.instagram.com" class="btn btn-social-icon btn-instagram navbar-btn"><span class="fa fa-instagram"></span></a>

                </div>
                <ul class="nav navbar-nav">                     
                    <li><a href="@Url.Action("Index","Home")">Home</a></li>
                    <li><a href="@Url.Action("Menus","Home")">Menus</a></li>
                    <li><a href="@Url.Action("OurStory","Home")">Our Story</a></li>
                    <li id="galleryButton"><a href="@Url.Action("Index","Gallery")">Gallery</a></li>                    
                </ul>

                 @Html.ActionLink("Book Now!","Book", "Home", null, new { @class = "btn btn-danger navbar-btn" })
                             
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Index","Admin")"><span class="glyphicon glyphicon-log-in"></span> Admin</a></li>                   
                </ul>
                

            </div>
        </nav>
        @RenderBody()
    <div>

    </div>
    
    </body>
</html>

GrillRoastBaste2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - GrillRoastBaste</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>